// /lib/bank.js
// Centralized list of supported countries and banks
// You can easily expand this list (up to 100+ safely)

export const BANKS = {
  "United States": [
    "Bank of America",
    "Chase",
    "Wells Fargo",
    "CitiBank",
    "US Bank",
    "PNC Bank",
  ],
  Canada: ["RBC", "TD Canada Trust", "Scotiabank", "BMO", "CIBC"],
  "United Kingdom": ["HSBC", "Barclays", "Lloyds", "NatWest", "Santander"],
  Nigeria: ["Zenith Bank", "GTBank", "UBA", "Access Bank", "First Bank"],
  Ghana: ["Ecobank", "GCB Bank", "Fidelity Bank Ghana", "Stanbic Ghana"],
  Kenya: ["Equity Bank", "KCB", "Co-operative Bank", "Stanbic Bank Kenya"],
  "South Africa": ["Standard Bank", "FNB", "Nedbank", "Absa", "Capitec"],
  Liberia: ["LBDI", "Ecobank Liberia", "UBA Liberia", "Global Bank Liberia"],
  "United Arab Emirates": [
    "Emirates NBD",
    "Abu Dhabi Commercial Bank",
    "Mashreq Bank",
  ],
  India: ["SBI", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra"],
  China: [
    "ICBC",
    "China Construction Bank",
    "Agricultural Bank of China",
    "Bank of China",
  ],
  Brazil: ["Itaú", "Bradesco", "Banco do Brasil", "Santander Brasil"],
  Mexico: ["BBVA Bancomer", "Banamex", "Santander Mexico", "Banorte"],
  Argentina: ["Banco Galicia", "Banco Nación", "Banco Santander Río"],
  Egypt: ["National Bank of Egypt", "Banque Misr", "CIB Egypt"],
  Morocco: ["Attijariwafa Bank", "BMCE Bank", "Banque Populaire"],
  Tunisia: ["BIAT", "Amen Bank", "UBCI"],
  Algeria: ["Banque Extérieure d’Algérie", "CNEP Bank", "BEA"],
  Turkey: ["Ziraat Bank", "Garanti BBVA", "İşbank"],
  SaudiArabia: ["Al Rajhi Bank", "National Commercial Bank", "SABB"],
  Qatar: ["QNB", "Doha Bank", "Commercial Bank of Qatar"],
  Kuwait: ["NBK", "Gulf Bank", "Burgan Bank"],
  Singapore: ["DBS Bank", "OCBC", "UOB"],
  Malaysia: ["Maybank", "CIMB", "RHB Bank"],
  Indonesia: ["Bank Mandiri", "BCA", "BNI"],
  Philippines: ["BDO", "Metrobank", "LandBank"],
  Thailand: ["Bangkok Bank", "Kasikorn Bank", "SCB"],
  Japan: ["MUFG Bank", "SMBC", "Mizuho Bank"],
  SouthKorea: ["Kookmin Bank", "Hana Bank", "Woori Bank"],
  Australia: ["Commonwealth Bank", "Westpac", "ANZ", "NAB"],
  NewZealand: ["ASB", "BNZ", "Westpac NZ", "Kiwibank"],
  France: ["BNP Paribas", "Société Générale", "Crédit Agricole"],
  Germany: ["Deutsche Bank", "Commerzbank", "Sparkasse", "ING"],
  Italy: ["UniCredit", "Intesa Sanpaolo", "Monte dei Paschi di Siena"],
  Spain: ["Santander", "BBVA", "CaixaBank"],
  Netherlands: ["ING", "Rabobank", "ABN AMRO"],
  Switzerland: ["UBS", "Credit Suisse", "Julius Baer"],
  Sweden: ["Swedbank", "SEB", "Nordea"],
  Norway: ["DNB", "SpareBank 1", "Nordea"],
  Denmark: ["Danske Bank", "Nordea Denmark", "Jyske Bank"],
  Finland: ["Nordea Finland", "OP Financial Group"],
  Poland: ["PKO Bank Polski", "Santander Poland", "mBank"],
  CzechRepublic: ["Česká spořitelna", "Komerční banka", "Moneta Money Bank"],
  Hungary: ["OTP Bank", "K&H Bank", "UniCredit Hungary"],
  Romania: ["BCR", "BRD", "Raiffeisen Bank Romania"],
  Ukraine: ["PrivatBank", "Oschadbank", "Ukreximbank"],
  SouthSudan: ["KCB South Sudan", "Equity Bank South Sudan"],
  SierraLeone: ["Rokel Commercial Bank", "Sierra Leone Commercial Bank"],
  Cameroon: ["Afriland First Bank", "UBA Cameroon", "BICEC"],
  Tanzania: ["CRDB Bank", "NMB Bank", "Stanbic Bank Tanzania"],
  Uganda: ["Stanbic Bank Uganda", "Centenary Bank", "dfcu Bank"],
  Rwanda: ["Bank of Kigali", "Equity Bank Rwanda", "I&M Bank Rwanda"],
  Zambia: ["Zanaco", "Stanbic Bank Zambia", "Absa Bank Zambia"],
  Zimbabwe: ["CBZ Bank", "Stanbic Zimbabwe", "Steward Bank"],
  Mozambique: ["BCI", "Millennium BIM", "Standard Bank Mozambique"],
  Botswana: ["First Capital Bank", "Stanbic Bank Botswana", "Absa Botswana"],
  Namibia: ["Bank Windhoek", "FNB Namibia", "Standard Bank Namibia"],
  Angola: ["BAI", "BFA", "Banco Económico"],
  Seychelles: ["MCB Seychelles", "Barclays Seychelles"],
  Mauritius: ["MCB", "SBM Bank", "ABC Banking"],
  Cyprus: ["Bank of Cyprus", "Hellenic Bank"],
  Greece: ["Alpha Bank", "Eurobank", "Piraeus Bank"],
  Israel: ["Bank Hapoalim", "Bank Leumi", "Discount Bank"],
  Pakistan: ["HBL", "UBL", "MCB", "Allied Bank"],
  Bangladesh: ["BRAC Bank", "Dutch-Bangla Bank", "Sonali Bank"],
  SriLanka: ["Bank of Ceylon", "Commercial Bank", "Peoples Bank"],
  Nepal: ["Nabil Bank", "Nepal Investment Bank", "Siddhartha Bank"],
  Afghanistan: ["Azizi Bank", "AIB", "Pashtany Bank"],
  Iran: ["Bank Melli", "Tejarat Bank", "Saderat Bank"],
  Iraq: ["Rafidain Bank", "Trade Bank of Iraq", "Bank of Baghdad"],
  Lebanon: ["Bank Audi", "Blom Bank", "Byblos Bank"],
  Jordan: ["Arab Bank", "Cairo Amman Bank", "Housing Bank"],
  Oman: ["Bank Muscat", "Bank Dhofar", "Oman Arab Bank"],
  Bahrain: ["National Bank of Bahrain", "Ahli United Bank"],
  Vietnam: ["Vietcombank", "Techcombank", "BIDV"],
  Laos: ["BCEL", "LaoViet Bank"],
  Cambodia: ["ABA Bank", "Acleda Bank", "Canadia Bank"],
  Myanmar: ["KBZ Bank", "AYA Bank", "CB Bank"],
  Mongolia: ["Khan Bank", "Golomt Bank", "Trade and Development Bank"],
  Kazakhstan: ["Halyk Bank", "Kaspi Bank"],
  Uzbekistan: ["Asaka Bank", "UzPromstroybank"],
  Georgia: ["TBC Bank", "Bank of Georgia"],
  Armenia: ["Ameriabank", "ACBA Bank"],
  Azerbaijan: ["International Bank of Azerbaijan", "Kapital Bank"],
  Belarus: ["Belarusbank", "Priorbank"],
  Estonia: ["LHV", "Swedbank Estonia"],
  Latvia: ["Citadele Banka", "SEB Latvia"],
  Lithuania: ["Swedbank Lithuania", "SEB Lithuania"],
  Iceland: ["Landsbankinn", "Íslandsbanki"],
  Ireland: ["AIB", "Bank of Ireland", "Permanent TSB"],
  Portugal: ["Caixa Geral de Depósitos", "Novo Banco"],
  Chile: ["Banco de Chile", "BancoEstado", "Santander Chile"],
  Colombia: ["Bancolombia", "Banco de Bogotá"],
  Peru: ["BCP", "Interbank", "BBVA Peru"],
  Venezuela: ["Banco de Venezuela", "Banesco"],
  Ecuador: ["Banco Pichincha", "Banco Guayaquil"],
  Bolivia: ["Banco Mercantil Santa Cruz", "Banco BISA"],
  Paraguay: ["Banco Itaú Paraguay", "Banco Regional"],
  Uruguay: ["Banco República", "Santander Uruguay"],
  Panama: ["Banco General", "Banistmo"],
  CostaRica: ["BAC Credomatic", "Banco Nacional"],
  Jamaica: ["NCB Jamaica", "Scotiabank Jamaica"],
  TrinidadTobago: ["Republic Bank", "First Citizens"],
  Barbados: ["CIBC FirstCaribbean", "Republic Bank Barbados"],
};
